// GENERATED by scripts/shaders.ts from reference/shaders/paint.frag — do not edit.
export const PAINT_FRAG = `#version 300 es
precision highp float;
// Mumbrane "Plein-air" paint pass: turns any input image (the scene pass, or a supplied texture)
// into oil paint — oriented bristle strokes in two sizes, impasto relief, canvas weave, varnish.
// Optional Replay-style interventions: scan slices and pixel-sorted blocks.
uniform vec2  uRes;
uniform sampler2D uSrc;      // source image (scene pass or a texture), sampled with uv in 0..1
uniform float uSeed;
uniform float uStroke;       // base stroke size in px of the output (coarse layer); fine = 0.45x
uniform float uSlices;       // 0 = off, 1 = on
uniform vec4  uSliceBand;    // y0, y1 (0..1 from bottom), line spacing px, displacement px
uniform float uBlocks;       // 0 = off, 1 = on
uniform vec3  uBlockA, uBlockB, uBlockC;
uniform vec3  uPaper;        // canvas/ground colour
out vec4 o;

float h12(vec2 p){ vec3 p3 = fract(vec3(p.xyx)*.1031); p3 += dot(p3, p3.yzx+33.33); return fract((p3.x+p3.y)*p3.z); }
vec2  h22(vec2 p){ vec3 p3 = fract(vec3(p.xyx)*vec3(.1031,.1030,.0973)); p3 += dot(p3, p3.yzx+33.33); return fract((p3.xx+p3.yz)*p3.zy); }
float vn(vec2 p){ vec2 i=floor(p), f=fract(p); vec2 u=f*f*(3.-2.*f);
  return mix(mix(h12(i),h12(i+vec2(1,0)),u.x), mix(h12(i+vec2(0,1)),h12(i+vec2(1,1)),u.x), u.y); }
float lum(vec3 c){ return dot(c, vec3(0.299, 0.587, 0.114)); }
vec3 src(vec2 px){ return texture(uSrc, clamp(px / uRes, 0.0, 1.0)).rgb; }

// structure direction at a point: along edges (perpendicular to the luminance gradient)
vec2 flowDir(vec2 px, float r){
  // Sobel-like gradient over a wide footprint (smoother than a 1-texel difference)
  float l  = lum(src(px + vec2(-r, 0))) + 0.5*(lum(src(px + vec2(-r, r))) + lum(src(px + vec2(-r, -r))));
  float rr = lum(src(px + vec2( r, 0))) + 0.5*(lum(src(px + vec2( r, r))) + lum(src(px + vec2( r, -r))));
  float d  = lum(src(px + vec2(0, -r))) + 0.5*(lum(src(px + vec2(r, -r))) + lum(src(px + vec2(-r, -r))));
  float u  = lum(src(px + vec2(0,  r))) + 0.5*(lum(src(px + vec2(r,  r))) + lum(src(px + vec2(-r,  r))));
  vec2 g = vec2(rr - l, u - d);
  float m = length(g);
  float ang = (vn(px*0.0035 + uSeed) - 0.5) * 0.8;
  vec2 base = vec2(cos(ang), sin(ang));
  if (m < 1e-4) return base;
  vec2 along = vec2(-g.y, g.x) / m;
  along *= sign(dot(along, base) + 1e-4);
  float k = smoothstep(0.06, 0.22, m);        // only real edges steer the stroke
  return normalize(mix(base, along, k));
}

// one layer of strokes: returns colour, coverage and height of the top-most stroke at p
void strokes(vec2 p, float size, float density, float layer, inout vec3 col, inout float cov, inout float height){
  vec2 cellId = floor(p / size);
  float bestZ = -1.0;
  for (int y = -2; y <= 2; y++) for (int x = -2; x <= 2; x++){
    vec2 id = cellId + vec2(x, y);
    vec2 rnd = h22(id + layer*17.0 + uSeed);
    float keep = h12(id*1.31 + layer*3.7 + uSeed);
    vec2 c = (id + 0.15 + 0.7*rnd) * size;
    vec3 sc = src(c);
    // detail-driven density for the fine layer
    float detail = abs(lum(src(c + vec2(size*0.5, 0))) - lum(src(c - vec2(size*0.5, 0))))
                 + abs(lum(src(c + vec2(0, size*0.5))) - lum(src(c - vec2(0, size*0.5))));
    if (keep > density + detail*6.0) continue;
    vec2 dir = flowDir(c, size*0.6);
    float len = size * (1.9 + 1.4*rnd.x);
    float wid = size * (0.62 + 0.36*rnd.y);
    vec2 d = p - c;
    float u = dot(d, dir), v = dot(d, vec2(-dir.y, dir.x));
    // slight curvature of the stroke
    v += 0.08 * u*u / max(size, 1.0) * (rnd.x - 0.5);
    vec2 q = vec2(max(abs(u) - (len*0.5 - wid*0.5), 0.0), v);
    float sd = length(q) - wid*0.5;
    // ragged, bristly edge
    float bristle = vn(vec2(u/size*2.2, v/wid*3.0 + rnd.y*31.0));
    sd += (bristle - 0.5) * wid * 0.30;
    if (sd < 0.0){
      float z = h12(id*2.13 + layer*9.1 + uSeed) + layer;
      if (z > bestZ){
        bestZ = z;
        // paint colour: sampled + small value/temperature jitter
        float j = h12(id*5.7 + uSeed) - 0.5;
        float tj = h12(id*3.3 + 1.7 + uSeed) - 0.5;
        vec3 pc = sc * (1.0 + j*0.16) + vec3(tj*0.05, tj*0.01, -tj*0.05);
        // occasional broken-colour fleck (impressionist): nudge towards a neighbour's colour
        if (h12(id*8.9 + uSeed) > 0.9) pc = mix(pc, src(c + dir*size*2.0 + vec2(-dir.y, dir.x)*size), 0.55);
        // bristle streaks along the stroke
        float streak = vn(vec2(u/size*0.8, v/wid*5.0 + rnd.x*17.0));
        pc *= 0.95 + 0.09*streak;
        col = pc;
        float across = clamp(abs(v)/(wid*0.5), 0.0, 1.0);
        float endFade = clamp(1.0 - (abs(u) - len*0.35)/(len*0.15 + 1.0), 0.0, 1.0);
        height = sqrt(max(1.0 - across*across, 0.0)) * (0.65 + 0.35*streak) * mix(0.55, 1.0, endFade) * (0.7 + 0.3*layer);
        cov = 1.0;
      }
    }
  }
}

void main(){
  vec2 p = gl_FragCoord.xy;
  // Intervention 1 — scan slices: displaced horizontal bands with paper rules
  float inBand = 0.0;
  if (uSlices > 0.5){
    float y = p.y / uRes.y;
    inBand = step(uSliceBand.x, y) * step(y, uSliceBand.y);
    if (inBand > 0.5){
      float row = floor(p.y / uSliceBand.z);
      p.x += (h12(vec2(row, uSeed)) - 0.5) * uSliceBand.w * 2.0;
    }
  }
  vec3 col = src(p);          // underpainting (visible only between strokes)
  float cov = 0.0, height = 0.0;
  strokes(p, uStroke, 0.98, 0.0, col, cov, height);
  vec3 colF = col; float covF = 0.0, hF = 0.0;
  strokes(p, uStroke*0.45, 0.35, 1.0, colF, covF, hF);
  if (covF > 0.5){ col = colF; height = hF; }

  // impasto: light from upper-left using screen-space derivatives of the paint height
  float hx = dFdx(height), hy = dFdy(height);
  vec3 n = normalize(vec3(-hx*1.3, -hy*1.3, 1.0));
  vec3 L = normalize(vec3(-0.55, 0.62, 0.56));
  float diff = dot(n, L);
  col *= 0.90 + 0.16*diff;
  col += vec3(1.0, 0.97, 0.9) * pow(max(dot(reflect(-L, n), vec3(0,0,1)), 0.0), 18.0) * 0.10 * height;

  // canvas weave, strongest where paint is thin
  vec2 wv = p * 0.9;
  float weave = (sin(wv.x*2.1) * sin(wv.y*2.1)) * 0.5 + 0.5;
  float grain = vn(p*0.8) * 0.6 + vn(p*2.3) * 0.4;
  col *= 1.0 - (0.012 + 0.05*(1.0 - cov)) * (weave*0.6 + grain*0.4);

  // varnish: warm, slightly compressed highlights, soft vignette
  col = mix(col, col*vec3(1.02, 1.0, 0.95), 0.6);
  col = col / (1.0 + max(col - 0.85, 0.0));
  vec2 vuv = gl_FragCoord.xy / uRes - 0.5;
  col *= 1.0 - 0.18*dot(vuv, vuv);

  // scan-slice rules
  if (inBand > 0.5){
    float r = mod(gl_FragCoord.y, uSliceBand.z);
    col = mix(col, uPaper, (1.0 - smoothstep(0.0, 1.6, r)) * 0.92);
  }
  // Intervention 2 — pixel-sorted blocks (three rectangles, seeded)
  if (uBlocks > 0.5){
    for (int i = 0; i < 3; i++){
      vec2 r = h22(vec2(float(i)*7.1, uSeed));
      vec2 bmin = vec2(0.08 + 0.78*r.x, 0.35 + 0.5*r.y) * uRes;
      vec2 bsz = vec2(0.05 + 0.06*h12(vec2(uSeed, float(i))), 0.035) * uRes.x;
      vec2 q = gl_FragCoord.xy - bmin;
      if (q.x > 0.0 && q.y > 0.0 && q.x < bsz.x && q.y < bsz.y){
        vec3 bc = i == 0 ? uBlockA : i == 1 ? uBlockB : uBlockC;
        float colv = h12(vec2(floor(q.x / 2.0), float(i) + uSeed));
        col = bc * (0.82 + 0.3*colv) * (0.92 + 0.08*smoothstep(0.0, bsz.y, q.y));
      }
    }
  }
  o = vec4(col, 1.0);
}
`
