// GENERATED by scripts/articles.ts from src/content/source/*.md — do not edit.
import type { Block } from './blocks.ts'

export const BODIES: Record<string, Block[]> = {
  "toward-field-based-intelligence": [
    {
      "type": "p",
      "text": "What if knowledge were not stored as rules or answers, but as the shape of a field?"
    },
    {
      "type": "p",
      "text": "That is the direction Mumbrane is pursuing. The field is produced by the data itself. Reasoning is what happens when a new input is dropped into the field and allowed to settle. The point where it comes to rest is the answer."
    },
    {
      "type": "h2",
      "text": "The data is the field",
      "id": "the-data-is-the-field"
    },
    {
      "type": "p",
      "text": "Pretrained encoders turn each piece of information into a point in a shared space. Each point shapes the field around it, the way a charge shapes the potential around it. There is no separate model on top: the stored data is the model. Whatever you put in becomes the truth."
    },
    {
      "type": "p",
      "text": "The charge picture is a metaphor. Fixed electric charges cannot hold a free charge in a stable resting place, so we build on smoother energy functions with real minima."
    },
    {
      "type": "h2",
      "text": "Fix the field, then ask",
      "id": "fix-the-field-then-ask"
    },
    {
      "type": "p",
      "text": "Building the field is the learning step. Once it is fixed, new inputs are shaped by the field but do not change it. A question enters as a new point, and its neighbors push and pull it until the forces balance. That resting point is what the system believes. Priority inputs carry more weight, so questions near them are pulled toward them harder."
    },
    {
      "type": "h2",
      "text": "Equilibrium is a candidate, not a guarantee",
      "id": "equilibrium-is-a-candidate-not-a-guarantee"
    },
    {
      "type": "p",
      "text": "A question can come to rest between similar memories rather than on any one of them. And nearness is not meaning: text encoders are known to place a sentence and its negation close together. So a resting point must be checked against the definitions that say what counts."
    },
    {
      "type": "h2",
      "text": "Close to known ideas",
      "id": "close-to-known-ideas"
    },
    {
      "type": "p",
      "text": "There is mathematics to borrow. **Modern Hopfield networks** store patterns as minima of an energy landscape and retrieve one by letting a query settle; transformer attention is one step of this update. **Mean shift** moves a point to the weighted average of its neighbors until it stops. **Energy-based models** choose the answer with the lowest energy. Per-item weights correspond to priority inputs."
    },
    {
      "type": "p",
      "text": "In short: memory as a landscape, inference as rolling downhill."
    },
    {
      "type": "h2",
      "text": "Moth as the first step",
      "id": "moth-as-the-first-step"
    },
    {
      "type": "p",
      "text": "In Moth Preview 004, supported English facts and definitions compile into a fixed, versioned field, and native constraint reasoning establishes each answer with its evidence. It does not establish continuous energy optimization; the [release evidence](/moth#evidence) describes what exists today."
    },
    {
      "type": "p",
      "text": "The open questions are concrete. Does a settled answer survive checking? How do accuracy and cost compare with appropriate baselines? And how far can field-based reasoning go in a physical universe, where causality limits which information can reach a decision?"
    }
  ],
  "introducing-moth-preview-004": [
    {
      "type": "p",
      "text": "Moth is the model Mumbrane is building for field-based intelligence: your data becomes the field, and a question settles where that field supports it. Preview 004 is the first step."
    },
    {
      "type": "h2",
      "text": "What it does",
      "id": "what-it-does"
    },
    {
      "type": "p",
      "text": "You author supported English facts, definitions and interpretation skills. Moth compiles them into a fixed, versioned field; existing local BGE assets take part in compilation. A question asks whether an entity meets a definition. Native constraint reasoning works through the requirements, and a checked response gives the result in controlled English or JSON, with its evidence."
    },
    {
      "type": "h2",
      "text": "One example",
      "id": "one-example"
    },
    {
      "type": "code",
      "lang": "text",
      "text": "An approved supplier means a supplier who passed inspection.\nA purchase qualifies as a purchase-ready item when it has funds available and its supplier is an approved supplier.\natlas is a supplier and passed inspection.\norderone appoints atlas as its supplier and has funds available.",
      "label": "Example"
    },
    {
      "type": "p",
      "text": "Asked “Is orderone a purchase-ready item?”, the field establishes the classification, though no source line states it. This explains the example’s reasoning; it is not a runtime transcript."
    },
    {
      "type": "h2",
      "text": "Scope",
      "id": "scope"
    },
    {
      "type": "p",
      "text": "Asking never adds knowledge: to change the field, compile and load a new build. Preview 004 is a CLI package for macOS ARM64 and Python 3.11, with four small synthetic example worlds. It does not settle questions in a continuous field or weight facts by priority; that runtime is proposed work. See the [release evidence](/moth#evidence)."
    }
  ],
  "different-wording-different-meaning": [
    {
      "type": "p",
      "text": "In a field built by pretrained encoders, similar sentences land close together. That is useful, and a risk: text encoders are known to place a sentence and its negation near each other. If answers simply followed nearness, the field would blur differences that matter. So Moth keeps two jobs apart. Encoders help place what you supplied; declared vocabulary and definitions decide what counts."
    },
    {
      "type": "h2",
      "text": "Change a phrase, keep the meaning",
      "id": "change-a-phrase-keep-the-meaning"
    },
    {
      "type": "code",
      "lang": "text",
      "text": "Is orderone a purchase-ready item?\nDoes orderone meet the requirements for a purchase-ready item?",
      "label": "Example"
    },
    {
      "type": "p",
      "text": "Both admitted forms refer to the same entity and concept. A source update can also teach a new supported form, such as “selects” for “appoints”; an unexplained synonym does not establish its meaning."
    },
    {
      "type": "h2",
      "text": "Change a requirement, change the answer",
      "id": "change-a-requirement-change-the-answer"
    },
    {
      "type": "p",
      "text": "Replace “passed inspection” with “passed audit” in the supplier definition and the criterion changes. The phrases are close in wording, but they are separately declared properties: one does not establish the other. After a rebuild, the classification may change."
    },
    {
      "type": "h2",
      "text": "How to test it",
      "id": "how-to-test-it"
    },
    {
      "type": "p",
      "text": "Pair rewordings that should keep an answer with small edits that should change it, and review the evidence, not only the answer. See the [language contract](/developers/docs#language-contract)."
    }
  ],
  "when-the-field-cannot-establish-an-answer": [
    {
      "type": "p",
      "text": "In a field-based system, an answer is where a question comes to rest. Sometimes the field gives it nowhere supported to rest. Saying so is part of the answer."
    },
    {
      "type": "h2",
      "text": "One missing link",
      "id": "one-missing-link"
    },
    {
      "type": "code",
      "lang": "text",
      "text": "ordertwo is a purchase.\nbirch is a supplier and passed audit.\nordertwo has funds available and appoints birch as its supplier.",
      "label": "Example"
    },
    {
      "type": "p",
      "text": "Approval requires a passed inspection. Asked “Is ordertwo a purchase-ready item?”, the documented expected outcome is `NO_SUPPORTED_PROOF`. That does not mean birch failed inspection; the field has not been given that support. This describes the example’s expected result, not a captured runtime response."
    },
    {
      "type": "h2",
      "text": "Keep the reason",
      "id": "keep-the-reason"
    },
    {
      "type": "p",
      "text": "Unsupported wording, conflicting facts and a resource limit are different outcomes from missing support, and each needs a different next step. Moth reports each one separately instead of collapsing them into “no”."
    },
    {
      "type": "h2",
      "text": "Improve the field on purpose",
      "id": "improve-the-field-on-purpose"
    },
    {
      "type": "p",
      "text": "Adding an inspection fact supplies evidence; requiring an audit changes a definition. Both mean a new build. The old answer stays tied to its original build, and replay can verify it within the same runtime. It does not prove the source facts true in the outside world."
    }
  ]
}

export const LEGAL_BODIES: Record<'terms' | 'privacy', Block[]> = {
  "terms": [
    {
      "type": "h2",
      "text": "Using the site",
      "id": "using-the-site"
    },
    {
      "type": "p",
      "text": "You may use this site to learn about Mumbrane and contact the lab. Do not interfere with its operation, attempt unauthorized access, or use it in a way that violates applicable law."
    },
    {
      "type": "h2",
      "text": "Research materials",
      "id": "research-materials"
    },
    {
      "type": "p",
      "text": "Unless a page states otherwise, site content is provided for information and discussion. Research notes may describe hypotheses and incomplete work; they are not warranties, professional advice, or claims of a released system."
    },
    {
      "type": "h2",
      "text": "External services",
      "id": "external-services"
    },
    {
      "type": "p",
      "text": "Links to third-party sites and authentication services are governed by their own terms. Mumbrane is not responsible for content or services operated by third parties."
    },
    {
      "type": "h2",
      "text": "Changes and contact",
      "id": "changes-and-contact"
    },
    {
      "type": "p",
      "text": "We may update these terms as the site develops. Questions can be sent to [hello@mumbrane.com](mailto:hello@mumbrane.com)."
    }
  ],
  "privacy": [
    {
      "type": "h2",
      "text": "Information you provide",
      "id": "information-you-provide"
    },
    {
      "type": "p",
      "text": "When you contact Mumbrane, we may receive your name, email address, affiliation, and the contents of your message. If account access is enabled, the authentication provider may process the identifiers required to sign you in."
    },
    {
      "type": "h2",
      "text": "How information is used",
      "id": "how-information-is-used"
    },
    {
      "type": "p",
      "text": "We use submitted information to respond to inquiries, coordinate research, operate the site, maintain security, and comply with applicable obligations. We do not sell personal information."
    },
    {
      "type": "h2",
      "text": "Retention and access",
      "id": "retention-and-access"
    },
    {
      "type": "p",
      "text": "We keep information only for as long as it is useful for the purpose it was collected or required by law. You may ask about, correct, or request deletion of personal information by contacting [hello@mumbrane.com](mailto:hello@mumbrane.com)."
    },
    {
      "type": "h2",
      "text": "Updates",
      "id": "updates"
    },
    {
      "type": "p",
      "text": "This notice may change as the lab and its systems evolve. Material revisions will be reflected on this page."
    }
  ]
}
