// `node scripts/articles.ts` — converts the harvested article markdown (src/content/source/) into
// typed blocks in src/content/articleBodies.ts (BUILD_PLAN P8). The authors' wording is kept; only
// typography changes (spaced em dashes, curly quotes and apostrophes) and links to the old site
// become internal routes. Deterministic; tests/unit/articles.test.ts checks the output is current.
import { readFileSync, writeFileSync } from 'node:fs'
import { ARTICLES } from '../src/content/articles.ts'
import { type Block, slugify } from '../src/content/blocks.ts'

const OUT = 'src/content/articleBodies.ts'

// Old-site URLs → this site's routes (CONTENT §3.2: /releases is now /moth#evidence).
const LINK_MAP: Record<string, string> = {
  releases: '/moth#evidence',
  'releases#language-contract': '/moth#language-contract',
  'releases#qualification': '/moth#qualification',
}

export function rewriteLinks(text: string): string {
  return text.replace(/\]\(https:\/\/mumbrane\.ai\/([^)]*)\)/g, (_, path: string) => {
    const clean = path.replace(/\.md$/, '')
    return `](${LINK_MAP[clean] ?? `/${clean}`})`
  })
}

/** Typography outside `code` spans: spaced em dashes, curly quotes and apostrophes. */
export function typography(text: string): string {
  return text
    .split('`')
    .map((part, i) => {
      if (i % 2 === 1) return part // inside a code span
      return part
        .replace(/(\S)—(\S)/g, '$1 — $2')
        .replace(/"([^"]*)"/g, '“$1”')
        .replace(/(\w)'(\w)/g, '$1’$2')
        .replace(/(\s|^)'(\w)/g, '$1‘$2')
        .replace(/(\w)'/g, '$1’')
    })
    .join('`')
}

const clean = (s: string) => typography(rewriteLinks(s.trim()))

/**
 * Markdown (the subset the harvested articles use) → blocks. The leading H1 and the description
 * paragraph under it are skipped: the article header renders them from the metadata.
 */
export function convertMarkdown(md: string): Block[] {
  const body = md.replace(/^---\n[\s\S]*?\n---\n/, '')
  const lines = body.split('\n')
  const blocks: Block[] = []
  let i = 0
  // Skip "# Title" and the description line right after it.
  while (i < lines.length && !lines[i]?.startsWith('# ')) i++
  i += 2
  let para: string[] = []
  const flush = () => {
    if (para.length) blocks.push({ type: 'p', text: clean(para.join(' ')) })
    para = []
  }
  while (i < lines.length) {
    const line = lines[i] ?? ''
    if (line.startsWith('```')) {
      flush()
      const lang = line.slice(3).trim() || 'text'
      const code: string[] = []
      i++
      while (i < lines.length && !lines[i]?.startsWith('```')) code.push(lines[i++] ?? '')
      blocks.push({ type: 'code', lang, text: code.join('\n'), label: 'Example' })
    } else if (/^#{2,3} /.test(line)) {
      flush()
      const text = clean(line.replace(/^#{2,3} /, ''))
      blocks.push({ type: line.startsWith('### ') ? 'h3' : 'h2', text, id: slugify(text) })
    } else if (/^(- |\d+\. )/.test(line)) {
      flush()
      const ordered = /^\d+\. /.test(line)
      const items: string[] = []
      while (i < lines.length && /^(- |\d+\. )/.test(lines[i] ?? ''))
        items.push(clean((lines[i++] ?? '').replace(/^(- |\d+\. )/, '')))
      blocks.push({ type: 'list', ordered, items })
      continue
    } else if (line.startsWith('> ')) {
      flush()
      blocks.push({ type: 'quote', text: clean(line.slice(2)) })
    } else if (line.trim() === '') {
      flush()
    } else {
      para.push(line)
    }
    i++
  }
  flush()
  return blocks
}

export function sourcePath(a: { section: string; slug: string }): string {
  return `src/content/source/${a.section}_${a.slug}.md`
}

export function generate(): string {
  const bodies = Object.fromEntries(
    ARTICLES.map((a) => [a.slug, convertMarkdown(readFileSync(sourcePath(a), 'utf8'))]),
  )
  return [
    '// GENERATED by scripts/articles.ts from src/content/source/*.md — do not edit.',
    "import type { Block } from './blocks.ts'",
    '',
    `export const BODIES: Record<string, Block[]> = ${JSON.stringify(bodies, null, 2)}`,
    '',
  ].join('\n')
}

if (import.meta.main) {
  writeFileSync(OUT, generate())
  process.stdout.write(`${OUT}\n`)
}
