// `node scripts/images.ts` — encodes .cache/paintings/*.png (from scripts/paint.ts) for the web
// (DESIGN §8.3): AVIF + WebP at every width in public/paintings/, an 8–10 colour palette (median
// cut on a 160 px thumbnail) and a 24 px LQIP. Writes src/content/paintings.manifest.json and
// src/app/lqip.css (inline styles are blocked by the CSP, so placeholders are generated classes).
// Unchanged sources are not re-encoded; outputs are byte-identical on re-run.
import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import sharp from 'sharp'
import { PAINTINGS, WIDTHS } from '../src/content/paintings.ts'

export type Swatch = { hex: string; weight: number }
export type ManifestEntry = { id: string; width: number; height: number; palette: Swatch[]; lqip: string }

const SRC = '.cache/paintings'
const OUT = 'public/paintings'
const KB = 1024
/** BUILD_PLAN budgets for the 1600 w AVIF. */
export const BUDGET_1600 = { painting: 180 * KB, poster: 120 * KB } as const
const AVIF_QUALITIES = [62, 60, 58, 55, 52, 50, 48, 45] as const
const WEBP_QUALITY = 78
const SETTINGS = JSON.stringify({ WIDTHS, AVIF_QUALITIES, WEBP_QUALITY, BUDGET_1600, v: 1 })

const hex2 = (n: number) => Math.round(n).toString(16).padStart(2, '0')
export const toHex = ([r, g, b]: readonly number[]) => `#${hex2(r ?? 0)}${hex2(g ?? 0)}${hex2(b ?? 0)}`

/**
 * Median cut: split the box with the widest channel range at its median until `n` boxes; each box
 * becomes its mean colour weighted by its share of pixels. Sorted by weight, heaviest first.
 */
export function medianCut(rgb: Uint8Array, n = 10): Swatch[] {
  const count = Math.floor(rgb.length / 3)
  let boxes: number[][] = [Array.from({ length: count }, (_, i) => i)]
  const range = (box: number[], c: number) => {
    let lo = 255
    let hi = 0
    for (const i of box) {
      const v = rgb[i * 3 + c] ?? 0
      if (v < lo) lo = v
      if (v > hi) hi = v
    }
    return hi - lo
  }
  while (boxes.length < n) {
    let best = -1
    let bestChannel = 0
    let bestRange = 0
    boxes.forEach((box, bi) => {
      if (box.length < 2) return
      for (let c = 0; c < 3; c++) {
        const r = range(box, c)
        if (r > bestRange) [best, bestChannel, bestRange] = [bi, c, r]
      }
    })
    if (best < 0) break
    const box = boxes[best] ?? []
    const sorted = [...box].sort((a, b) => (rgb[a * 3 + bestChannel] ?? 0) - (rgb[b * 3 + bestChannel] ?? 0))
    const mid = sorted.length >> 1
    boxes = [...boxes.slice(0, best), sorted.slice(0, mid), sorted.slice(mid), ...boxes.slice(best + 1)]
  }
  return boxes
    .filter((b) => b.length > 0)
    .map((box) => {
      const sum = [0, 0, 0]
      for (const i of box) for (let c = 0; c < 3; c++) sum[c] = (sum[c] ?? 0) + (rgb[i * 3 + c] ?? 0)
      return {
        hex: toHex(sum.map((s) => s / box.length)),
        weight: Math.round((box.length / count) * 1000) / 1000,
      }
    })
    .sort((a, b) => b.weight - a.weight || a.hex.localeCompare(b.hex))
}

export function lqipCss(entries: readonly ManifestEntry[]): string {
  const rules = entries.map(
    (e) =>
      `.lqip-${e.id} {\n  background: ${e.palette[0]?.hex ?? 'transparent'} url("${e.lqip}") center / cover no-repeat;\n}`,
  )
  return `/* GENERATED by scripts/images.ts — do not edit. Painting placeholders (DESIGN §8.3). */\n${rules.join('\n')}\n`
}

async function encode(id: string, png: string, poster: boolean): Promise<ManifestEntry> {
  const img = sharp(png)
  const { width = 0, height = 0 } = await img.metadata()
  // Pick the AVIF quality that keeps the 1600 w file inside its budget; use it for every width.
  const budget = poster ? BUDGET_1600.poster : BUDGET_1600.painting
  let quality: number = AVIF_QUALITIES.at(-1) ?? 45
  for (const q of AVIF_QUALITIES) {
    const size = (await sharp(png).resize({ width: 1600 }).avif({ quality: q, effort: 6 }).toBuffer()).length
    if (size <= budget) {
      quality = q
      break
    }
  }
  for (const w of WIDTHS) {
    const resized = sharp(png).resize({ width: w })
    await resized.clone().avif({ quality, effort: 6 }).toFile(`${OUT}/${id}-${w}.avif`)
    await resized.clone().webp({ quality: WEBP_QUALITY }).toFile(`${OUT}/${id}-${w}.webp`)
  }
  const thumb = await sharp(png).resize({ width: 160 }).removeAlpha().raw().toBuffer()
  const tiny = await sharp(png).resize({ width: 24 }).webp({ quality: 50 }).toBuffer()
  const entry = {
    id,
    width,
    height,
    palette: medianCut(new Uint8Array(thumb), 10),
    lqip: `data:image/webp;base64,${tiny.toString('base64')}`,
  }
  process.stdout.write(`encoded ${id} (AVIF q${quality})\n`)
  return entry
}

async function main() {
  mkdirSync(OUT, { recursive: true })
  const entries: ManifestEntry[] = []
  for (const spec of PAINTINGS) {
    const png = `${SRC}/${spec.id}.png`
    if (!existsSync(png)) throw new Error(`${png} missing — run node scripts/paint.ts first`)
    const hash = createHash('sha256').update(readFileSync(png)).update(SETTINGS).digest('hex').slice(0, 16)
    const stampPath = `${SRC}/${spec.id}.enc.json`
    const outputs = WIDTHS.flatMap((w) => [`${OUT}/${spec.id}-${w}.avif`, `${OUT}/${spec.id}-${w}.webp`])
    const stamp = existsSync(stampPath)
      ? (JSON.parse(readFileSync(stampPath, 'utf8')) as { hash: string; entry: ManifestEntry })
      : undefined
    if (stamp?.hash === hash && outputs.every((o) => existsSync(o))) {
      entries.push(stamp.entry)
      process.stdout.write(`unchanged ${spec.id}\n`)
      continue
    }
    const entry = await encode(spec.id, png, spec.scene === 'membrane')
    writeFileSync(stampPath, JSON.stringify({ hash, entry }))
    entries.push(entry)
  }
  writeFileSync('src/content/paintings.manifest.json', `${JSON.stringify(entries, null, 2)}\n`)
  writeFileSync('src/app/lqip.css', lqipCss(entries))
}

if (import.meta.main) await main()
