// `node scripts/shaders.ts` — copies the tested GLSL in reference/shaders/*.frag into
// src/shaders/*.ts as string exports, byte for byte (reference/shaders/README: port without
// changing the maths). Idempotent; tests/unit/gl.test.ts asserts the copies are exact.
import { readFileSync, writeFileSync } from 'node:fs'

export const SHADERS = ['membrane', 'scene', 'paint'] as const

export function toModule(name: string, glsl: string): string {
  if (glsl.includes('`') || glsl.includes('${')) throw new Error(`${name}.frag cannot be a template literal`)
  const constName = `${name.toUpperCase()}_FRAG`
  return [
    `// GENERATED by scripts/shaders.ts from reference/shaders/${name}.frag — do not edit.`,
    `export const ${constName} = \`${glsl}\``,
    '',
  ].join('\n')
}

function main() {
  for (const name of SHADERS) {
    const glsl = readFileSync(`reference/shaders/${name}.frag`, 'utf8')
    writeFileSync(`src/shaders/${name}.ts`, toModule(name, glsl))
    process.stdout.write(`src/shaders/${name}.ts\n`)
  }
}

if (import.meta.main) main()
